# ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||

#       Geographic and Ecological Earth Observation (GEEO) PARAMETER FILE

#                                   Version 1.0
#                          Copyright (c) 2025, Leon Nill
#   Biogeography Lab | Department of Geography | Humboldt-Universität zu Berlin
#              mail: leon.nill@geo.hu-berlin.de | GitHub: leonsnill


# ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||


# ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
#                                    LEVEL-2
# ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||

# -------------------------------------------------------------------------------
#                                 SPACE AND TIME                               
# -------------------------------------------------------------------------------

# Global time settings
YEAR_MIN: 2023                           # Minimum year
YEAR_MAX: 2023                           # Maximum year
MONTH_MIN: 1                             # Minimum month
MONTH_MAX: 12                            # Maximum month
DOY_MIN: 1                               # Minimum day of year
DOY_MAX: 366                             # Maximum day of year

# alternative (overwrites all of the above)
DATE_MIN: null                           # YYYYMMDD
DATE_MAX: null                           # YYYYMMDD       

# Region of Interest (ROI). One of the following options: 
# - Single point as [lon, lat]
# - Rectangle as [lon, lat, lon, lat]
# - Polygon as [[lon1, lat1], [lon2, lat2], ..., [lon1, lat1]]
# - Path / or geopandas object vector file (e.g. shapefile, geopackage, geojson)
ROI: [12.9, 52.2, 13.9, 52.7]
ROI_SIMPLIFY_GEOM_TO_BBOX: false         # Simplify geometry to bounding box


# -------------------------------------------------------------------------------
#                            TIME SERIES STACK (TSS)
#                        SENSOR AND DATA QUALITY SETTINGS                          
# -------------------------------------------------------------------------------

# ------------------------------------
#          Sensor Selection
# ------------------------------------
# Time Series Stack (TSS) is the raw (preprocessed) ImageCollection 
# Landsat 4-9 Level 2, Collection 2, Tier 1
# Sentinel-2 Level-2A
# Choosing >1 results in a merge of sensor constellations. 
SENSORS:                                 # Options: L9, L8, L7, L5, L4, S2, HLS, HLSL30, HLSS30
- L9
- L8
- L7
- L5
- L4
MAX_CLOUD: 75                            # Maximum (land) cloud cover percentage

# ------------------------------------
#          Masking
# ------------------------------------
# Landsat settings
EXCLUDE_SLCOFF: false                    # Exclude Landsat-7 ETM+ SLC-off
GCP_MIN_LANDSAT: 1                       # Min Ground Control Points for Landsat
MASKS_LANDSAT:                           # Landsat masks (null, cloud, cshadow,
- cloud                                  # snow, fill, dilated)
- cshadow
- snow
- fill
- dilated
MASKS_LANDSAT_CONF: Medium               # Confidence level for Landsat masks (Medium, High)

# Sentinel-2 settings
MASKS_S2: CPLUS                          # S2 masking (null, CPLUS, PROB, SCL)
MASKS_S2_CPLUS: 0.6                      # S2 CPLUS: Threshold for mask
MASKS_S2_PROB: 30                        # PROB: Probability threshold for mask
MASKS_S2_NIR_THRESH_SHADOW: 0.2          # PROB: Threshold NIR-based shadow mask

# HLS masking (Fmask)
MASKS_HLS:
- cloud                                  # snow, fill, dilated)
- cshadow
- snow

# General advanced masking
ERODE_DILATE: false                      # Erode an dilate mask
ERODE_RADIUS: 60                         # Erosion radius (meters)
DILATE_RADIUS: 120                       # Dilation radius (meters)
ERODE_DILATE_SCALE: 60                   # Pixel scale for erode/dilate operations
BLUE_MAX_MASKING: null                   # Maximum blue reflectance to mask [0, 1]


# -------------------------------------------------------------------------------
#                           BANDS | INDICES | FEATURES
# -------------------------------------------------------------------------------

# ------------------------------------
#         Available Features
# ------------------------------------
# Available bands:
# BLU, GRN, RED, NIR, SW1, SW2 (Landsat+Sentinel-2)
# LST (Landsat, if LST was processed for scene)
# RE1, RE2, RE3, RE4 (Sentinel-2)
# NDVI, EVI, NBR, NDMI, NDWI, MDWI, NDB, TCG, TCB, TCW, SWR, DEM (Copernicus)
FEATURES:
- BLU
- GRN
- RED
- NIR
- SW1
- SW2
- NDVI
#- MY_FORMULA1
#- MY_FORMULA2

# ------------------------------------
#   Custom Features from Functions
# ------------------------------------
CUSTOM_FORMULAS:                         # custom formulas (optional)
  MY_FORMULA1:                                  # will become also the bandname if in FEATURES
    formula: "(G-SW1)/(G+SW1)"
    variable_map:
      G: GRN
      SW1: SW1
  MY_FORMULA2:                                  # will become also the bandname if in FEATURES
    formula: "MY_FORMULA/2"
    variable_map:
      MY_FORMULA: MY_FORMULA1

# ------------------------------------
#        Linear Unmixing (UMX)
# ------------------------------------
UMX: null                                # endmeber dictionary
# {'Class1': [100, 230, ..., 123], 'Class2': [24, ...], ...} must match FEATURES
# Unmixing settings
UMX_SUM_TO_ONE: true                     # Sum to one constraint
UMX_NON_NEGATIVE: true                   # Non-negative constraint
UMX_REMOVE_INPUT_FEATURES: true          # Keep only unmixing features


# -------------------------------------------------------------------------------
#                           CUSTOM IMAGE COLLECTION (CIC)
# -------------------------------------------------------------------------------

# Custom ImageCollection (note that if CIC is defined, TSS from above will not be processed)
CIC: null                                # path to ee.ImageCollection in catalogue 
#                                         (e.g GOOGLE/SATELLITE_EMBEDDING/V1/ANNUAL)
CIC_FEATURES: null                       # bands of CIC to include (null = all)


# -------------------------------------------------------------------------------
#                             TIME SERIES MOSAIC (TSM)
# -------------------------------------------------------------------------------

# Time Series Mosaic (TSM) create spatially-consistent mosaic for unique dates
TSM: false                               # Time Series Mosaic (TSM)
TSM_BASE_IMGCOL: TSS                     # (TSS, CIC)


# ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
#                                    LEVEL-3
# ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||

# -------------------------------------------------------------------------------
#                         TEMPORAL SUBWINDOWS | FOLDING
#                              (for STMs and PBCs)                               
# -------------------------------------------------------------------------------

# Simple calendar-based folding
FOLD_YEAR: false                         # Fold per year
FOLD_MONTH: false                        # Fold per month

# Custom folding (format either range (e.g. [2020-2021, 2023-2024] | [01-03, 05-07])
# or target+-offset (e.g. [1996+-1] | [265+-30]). Combinations are possible.
FOLD_CUSTOM: {
  year: null,                            # [YYYY-YYYY, ...] / [YYYY+-OFFSET, ...]
  month: null,                           # [MM-MM, ...] / [MM+-OFFSET, ...]
  doy: null,                             # [DOY-DOY, ...] / [DOY+-OFFSET, ...
  date: null                             # [YYYYMMDD-YYYYMMDD, ...] / [YYYYMMDD+-OFFSET, ...]
}


# -------------------------------------------------------------------------------
#                       NUMBER of VALID OBSERVATIONS (NVO)
# -------------------------------------------------------------------------------

NVO: false
NVO_FOLDING: false


# -------------------------------------------------------------------------------
#                         TIME SERIES INTERPOLATION (TSI)
# -------------------------------------------------------------------------------

TSI: null                                # (null, WLIN, 1RBF, 2RBF, 3RBF)  
TSI_BASE_IMGCOL: TSS                     # (TSS, TSM, CIC)

# Interpolation settings
INTERVAL: 16                             # Interpolation interval (days)
INTERVAL_UNIT: day                       # day, month, year
INIT_JANUARY_1ST: false                  # Initialize interval on Jan 1st
SIGMA1: 16                               # Sigma1 of RBF function (in days)
SIGMA2: 32                               # Sigma2 of RBF function (in days)
SIGMA3: 64                               # Sigma3 of RBF function (in days)
WIN1: 16                                 # Window1 for RBF (in days)
WIN2: 32                                 # Window2 for RBF (in days)
WIN3: 64                                 # Window3 for RBF (in days)
BW1: 4                                   # Weight for WIN1
BW2: 8                                   # Weight for WIN2


# -------------------------------------------------------------------------------
#                        SPECTRAL TEMPORAL METRICS (STM)
# -------------------------------------------------------------------------------

STM: null                                # null or list (min, p5, p10, p15, ..., 
#                                          p95, max, mean, median, stdDev, 
#                                          variance, skew, kurtosis)
# Collection to derive STMs from
STM_BASE_IMGCOL: TSS                     # (TSS, TSM, TSI, CIC)

# Folding: temporal subwindows
STM_FOLDING: false                       # use folding settings from above
STM_FOLDING_LIST_ITER: false             # false (joining) or true (list iteration)


# -------------------------------------------------------------------------------
#                        PIXEL-BASED COMPOSITING (PBC)
# -------------------------------------------------------------------------------

PBC: null                                # null, BAP, MAX-RNB, NLCD, or 'FEATURE' (e.g. NDVI, NBR) 
PBC_BASE_IMGCOL: TSS                     # (TSS, TSM, TSI, CIC)

# Folding: temporal subwindows
PBC_FOLDING: false                       # use folding settings from above

# PBC settings
PBC_INVERT_QUALITY_METRIC: false         # invert if minima are better
#                                          (uses ee.ImageCollection.qualityMosaic())

# Best-Available-Pixel (BAP) Settings            
PBC_BAP_DOY_EQ_YEAR: 30                  # DOY-offset where DOY-score = YEAR-score
PBC_BAP_MAX_CLOUDDISTANCE: 500           # Cloud distance (m) where CLOUD-score = 1
PBC_BAP_MIN_CLOUDDISTANCE: 0             # Cloud distance (m) where CLOUD-score = 0
PBC_BAP_WEIGHT_DOY: 0.6                  # Weight for DOY-score (seasonal consistency)
PBC_BAP_WEIGHT_YEAR: 0.2                 # Weight for YEAR-score (annual consistency)
PBC_BAP_WEIGHT_CLOUD: 0.2                # Weight for CLOUD-score


# ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
#                                    LEVEL-4
# ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||

# -------------------------------------------------------------------------------
#                         LAND SURFACE PHENOLOGY (LSP)
# -------------------------------------------------------------------------------

LSP: null                                # null, POLAR
LSP_BASE_IMGCOL: TSI                     # TSI (strongly recommended!), CIC
LSP_BAND: NDVI                           # Band to use for LSP calculation
LSP_YEAR_MIN: null                       # Minimum year for LSP calculation
LSP_YEAR_MAX: null                       # Maximum year for LSP calculation

# seasonal LSP adjustment
LSP_ADJUST_SEASONAL: false               # seasonal instead of global start/end DOYs
LSP_ADJUST_SEASONAL_MAX_DAYS: 40         # maximum adjustment in days



# ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
#                                    EXPORT
# ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||

# -------------------------------------------------------------------------------
#                               IMAGE SETTINGS
# -------------------------------------------------------------------------------

PIX_RES: 30                              # Pixel resolution (in meters)

CRS: EPSG:4326                           # EPSG, WKT string, UTM, Mollweide, or GLANCE continent (AF,AN,AS,EU,OC,NA,SA)
CRS_TRANSFORM: null                      # Affine transform to use for export        
IMG_DIMENSIONS: null                     # Image dimensions (widthxheight) in pixels (requires CRS_TRANSFORM)

RESAMPLING_METHOD: null                  # null (nearest neighbour), bilinear, bicubic

DATATYPE: int16                          # uint8, int8, uint16, int16, uint32, int32, float, double
DATATYPE_SCALE: 10000                    # Scale factor (check DATATYPE)
NODATA_VALUE: -9999                      # Output no data value (for certain exports like LSP not used)


# -------------------------------------------------------------------------------
#                            PRODUCTS TO EXPORT
# -------------------------------------------------------------------------------

EXPORT_IMAGE: false                      # Export Image
EXPORT_TABLE: false                      # Export Table 

EXPORT_TSS: false                        # Export TSS
EXPORT_CIC: false                        # Export CIC 
EXPORT_TSM: false                        # Export TSM
EXPORT_NVO: false                        # Export NVO 
EXPORT_TSI: false                        # Export TSI 
EXPORT_STM: false                        # Export STM 
EXPORT_PBC: false                        # Export PBC
EXPORT_LSP: false                        # Export LSP


# -------------------------------------------------------------------------------
#                           GENERAL EXPORT SETTINGS
# -------------------------------------------------------------------------------

EXPORT_LOCATION: Drive                   # (Drive, Asset)
EXPORT_DIRECTORY: null                   # null (Drive main folder) / assetId
EXPORT_DESC: GEEO                        # Image description included in filename
EXPORT_DESC_DETAIL_TIME: false           # Append detailed time description
EXPORT_BANDNAMES_AS_CSV: false           # Soft requirement for n-bands > 100
EXPORT_TABLE_FORMAT: CSV                 # CSV, GeoJSON, KML, KMZ, SHP, TFRecord
EXPORT_TABLE_METHOD: reduceRegions       # 'reduceRegions' or 'reduceRegion'
EXPORT_TABLE_TILE_SCALE: 1               # Compute tile size [0.1, 16]
EXPORT_TABLE_BUFFER: null                # Buffer features before reduction (meters)
EXPORT_TABLE_REDUCER: first              # Reducer used to extract values
EXPORT_TABLE_DROP_NODATA: false          # Drop nodata rows from table
# ATTENTION: The folllowing can result in many exports and be highly inefficient!
EXPORT_PER_FEATURE: false                # Export separate img per feature/band
EXPORT_PER_TIME: false                   # Export separate img per time (i.e., every img in imgcol)

# EOF